### ISSUE TITLE
Better implementation of init command

### ISSUE THREAD

**Issue by bkrainer** [HubSpot/local-cms-server-cli#18]
Right now this just calls `svn export` which is weird

**Comment by timmfin** [comment]
Continuing from https://github.com/HubSpot/local-cms-server-cli/pull/10#issuecomment-460427689:

> yeah, the svn thing is only meant to be temporary: https://github.com/HubSpot/local-cms-server-cli/issues/18
> 
> I think using those raw links would work for the initialization of single files, but not the subdirectories that can be initialized (i.e. the `context` directory and the sample `designs` directory)

Ah, good point. I didn't realize directory fetches were needed.

Another thought is to publish those files and directories to some static, versioned location as a part of the process to publish a new version of `local-cms-server-cli`. I suspect you'll eventually run into issues of older versions of the library breaking when they pulled down latest master version of a config file, so having these configuration assets uploaded to S3/some CDN (or copied directly into versioned npm package itself?) would probably be a good idea anyway.

**Comment by bkrainer** [comment]
> I suspect you'll eventually run into issues of older versions of the library breaking when they pulled down the latest master version of a config file

Great point. Using S3 or publishing directly to the npm package would both work. I'll go forward with one of those solutions when I get around to tackling this issue

**Comment by bkrainer** [comment]
Went with publishing the initializable things within the npm package: https://github.com/HubSpot/local-cms-server-cli/commit/b684bfa77ad24554dd15351c76adc64001c6774a
