### ISSUE TITLE
Bug in ternary expression

### ISSUE THREAD

**Issue by kaifresh** [HubSpot/local-cms-server-cli#72]
Hey @bkrainer,

I have been using this module with my colleagues and we noticed that on [this line](https://github.com/HubSpot/local-cms-server-cli/blob/f585e9e819e719767aed5242cbb23a5085e11da4/defaults/context/default-modules/123/1155241/module.html#L14), the ternary operator evaluates to "&" regardless of its truthiness. This looks like a bug and I think the false branch should evaluate to a "?". What do you think?

CC @techieshark

**Comment by bkrainer** [comment]
Hey @kaifresh,

I should point out that this project is deprecated and not being actively maintained. However the issue you pointed out appears to exist in the actual `@hubspot/social_sharing` module used in HubSpot sites, so I've filed an issue with one of our teams internally to investigate. Thanks!
